Move function to check youtube domain to common class
triplebanana/triple_banana pull request #781
Opened 2020-10-19 15:13 UTC by jdragonbae

This patch means moving the function to check the youtube domain to the common
utils class. Cause, this function is useful to use in other code.

Refs: #776

2020-10-19 21:45 UTC, romandev requested changes
The method doesn't have a dependency with upstream. Therefore, there is no reason to move it to Banana layer.

2020-10-20 01:26 UTC, jdragonbae commented
> The method doesn't have a dependency with upstream. Therefore, there is no reason to move it to Banana layer.

Ack. Thanks.

2020-10-20 15:25 UTC, romandev commented on src/org/triple/banana/util/UrlUtil.java
> +    public static boolean isYoutubeDomainUrl(String urlString) {
Make the string non-null

2020-10-20 15:25 UTC, romandev commented on src/org/triple/banana/util/UrlUtil.java
> +public class UrlUtil {
Make this class's name `YouTubeUtil` or `YouTubeHelper` or other name?

2020-10-20 15:39 UTC, jdragonbae commented on src/org/triple/banana/util/UrlUtil.java
> +public class UrlUtil {
`YouTubeUtil` looks good to me!

2020-10-20 15:43 UTC, jdragonbae commented on src/org/triple/banana/util/UrlUtil.java
> +    public static boolean isYoutubeDomainUrl(String urlString) {
Done.

2020-10-20 23:23 UTC, romandev approved these changes
LGTM

2020-10-20 23:24 UTC, merged