Implement QuickMenuActionProvider to support QuickMenu
triplebanana/triple_banana pull request #946
Opened 2020-12-17 05:28 UTC by jdragonbae

This patch implements QuickMenuActionProvider to support QuickMenu
Button's action. It will be used when a user clicks QuickMenuButton.

Refs: #936

2020-12-18 02:03 UTC, romandev commented on src/org/triple/banana/quick_menu/QuickMenuActionProvider.java
> +enum QuickMenuActionProvider {
Don't use `enum` and please separate interface and implementation.

2020-12-18 02:03 UTC, romandev commented on src/org/triple/banana/quick_menu/QuickMenuActionProvider.java
> +    void toggleDarkMode() {
This is not good. The class name is `ActionProvider`. You should provide `Action`. It means that the `Action` class should be defined. The `Action` class is abstraction of behavior.

2020-12-18 02:36 UTC, jdragonbae commented on src/org/triple/banana/quick_menu/QuickMenuActionProvider.java
> +enum QuickMenuActionProvider {
Ack.

2020-12-18 02:36 UTC, jdragonbae commented on src/org/triple/banana/quick_menu/QuickMenuActionProvider.java
> +    void toggleDarkMode() {
@romandev Thanks for the guidance. I'll try to it.

2020-12-20 01:21 UTC, romandev approved these changes

2020-12-20 01:21 UTC, romandev commented on src/org/triple/banana/quick_menu/QuickMenuControllerImpl.java
> +        switch (id) {
This `switch` statement looks unnecessary because you are getting the action from `HashMap` internally. Do you have a special reason?

2020-12-20 01:21 UTC, romandev commented on src/org/triple/banana/quick_menu/action/QuickMenuActionProviderImpl.java
> +    public @Nullable QuickMenuAction getAction(final @NonNull QuickMenuButtonId id) {
Make non-null. If the action is null, return empty action instead of null.

2020-12-20 01:21 UTC, romandev commented on src/org/triple/banana/quick_menu/QuickMenuViewModelImpl.java
> +        Map<QuickMenuButtonId, ButtonInfo> buttons = new HashMap<QuickMenuButtonId, ButtonInfo>() {
Is this correct? I think the buttons should keep their order.

2020-12-20 01:21 UTC, romandev commented on src/org/triple/banana/quick_menu/action/QuickMenuActionProviderImpl.java
> +        mFactory = new QuickMenuActionFactoryImpl();
Looks unnecessary.

2020-12-20 01:21 UTC, romandev commented on src/org/triple/banana/quick_menu/action/QuickMenuActionFactoryImpl.java
> +// Copyright 2020 The Triple Banana Authors. All rights reserved.
This class is unnecessary. Why do you need this class?
If you would want to initialize the actions lazily, you can use a `Supplier` instead but there is no benefit, IMHO.

2020-12-20 01:21 UTC, romandev commented on src/org/triple/banana/quick_menu/action/QuickMenuActionProviderImpl.java
> +        mActionMap = new HashMap<>();
You can define the provider data here.
```
mActionMap = new HashMap() {{
    add(dark_mode, () -> {
        // Do something
    });
}};
```

2020-12-20 01:22 UTC, romandev requested changes
accidentally lgtm.

2020-12-20 09:30 UTC, jdragonbae commented on BUILD.gn
>      "//triple_banana/src/org/triple/banana/quick_menu/QuickMenuViewImpl.java",
SGTM. I'll try to add `MockViewImpl`.

2020-12-20 09:30 UTC, jdragonbae commented on src/org/triple/banana/quick_menu/QuickMenuViewModelImpl.java
> +                put(QuickMenuButtonId.DARK_MODE,
Ack.

2020-12-20 09:31 UTC, jdragonbae commented on src/org/triple/banana/quick_menu/action/QuickMenuDarkModeAction.java
> +class QuickMenuDarkModeAction implements QuickMenuAction {
Ack.

2020-12-20 09:32 UTC, jdragonbae commented on src/org/triple/banana/quick_menu/action/QuickMenuActionFactoryImpl.java
> +// Copyright 2020 The Triple Banana Authors. All rights reserved.
Ack.

2020-12-20 09:32 UTC, jdragonbae commented on src/org/triple/banana/quick_menu/action/QuickMenuActionProviderImpl.java
> +        mFactory = new QuickMenuActionFactoryImpl();
Ack.

2020-12-20 12:57 UTC, romandev commented on banana_cake/interfaces/java/org/banana/cake/interfaces/BananaToolbarManager.java
> +    void openQuickMenu();
This is unnecessary because the QuickMenu is not upstream code. You should add the method in ButtonId.

2020-12-20 12:57 UTC, romandev commented on banana_cake/java/org/banana/cake/CakeToolbarManager.java
> +    public void openQuickMenu() {
This should be defined in ButtonId

2020-12-20 12:57 UTC, romandev commented on src/org/triple/banana/quick_menu/QuickMenuButtonId.java
> +// Copyright 2020 The Triple Banana Authors. All rights reserved.
This is unnecessary. Please use R.id.xxxx instead.

2020-12-20 12:57 UTC, romandev commented on BUILD.gn
> +    "//triple_banana/src/org/triple/banana/quick_menu/QuickMenuButtonId.java",
This looks unnecessary. Please use the R.id.xxxx instead.

2020-12-20 12:57 UTC, romandev commented on banana_cake/java/org/banana/cake/CakeToolbarManager.java
> +        QuickMenuFactory factory = new QuickMenuFactoryImpl();
The impl class should not expose to other external modules.
Instead add a static method to QuickMenuFactory interface as follows:
```
public interface QuickMenuFactory {
    ...
    static QuickMenuFactory create() {
        return new QuickMenuFactoryImpl();
    }
    ...
}
```

2020-12-20 12:57 UTC, romandev commented on src/org/triple/banana/quick_menu/QuickMenuActionProviderImpl.java
> +        if (id == QuickMenuButtonId.DARK_MODE) {
I already commented[1], I think this should be map instead of `if-statement`
[1] https://github.com/triplebanana/triple_banana/pull/946#discussion_r546305169

2020-12-20 12:57 UTC, romandev commented on src/org/triple/banana/quick_menu/QuickMenuViewModelImpl.java
> +        Map<Integer, ButtonInfo> getButtons() {
This should return `List<ButtonInfo>`.

2020-12-20 12:57 UTC, romandev commented on src/org/triple/banana/quick_menu/QuickMenuViewModelImpl.java
> +            }
I think that the setter/getter looks unnecessary. It's a reason why we define the members as `non-private`.

2020-12-20 12:57 UTC, romandev commented on src/org/triple/banana/quick_menu/QuickMenuControllerImpl.java
> +        mQuickMenuViewModel.getEditor().getButtons().put(QuickMenuButtonId.DARK_MODE,
mQuickMenuViewModel.getEditor().getEditor().addButton(R.id.xxx, R.drawable.xxx, R.string.xxx);

2020-12-20 14:05 UTC, jdragonbae commented on banana_cake/java/org/banana/cake/CakeToolbarManager.java
> +        QuickMenuFactory factory = new QuickMenuFactoryImpl();
Thanks for the review. Ack.

2020-12-20 14:40 UTC, jdragonbae commented on src/org/triple/banana/quick_menu/QuickMenuActionProviderImpl.java
> +        if (id == QuickMenuButtonId.DARK_MODE) {
Ack. Thanks!

2020-12-20 14:46 UTC, jdragonbae commented on src/org/triple/banana/quick_menu/QuickMenuViewModelImpl.java
> +            }
Ack.

2020-12-20 14:58 UTC, jdragonbae commented on banana_cake/interfaces/java/org/banana/cake/interfaces/BananaToolbarManager.java
> +    void openQuickMenu();
Thanks for the review. In order to show the quick menu view, need a `Context`. 
So, I used `ChromeTabbedActivity activity = getChromeTabbedActivity();` in CakeToolbarManager.
Is there another way to get `Context` in ButtonId?

2020-12-20 15:04 UTC, jdragonbae commented on src/org/triple/banana/quick_menu/QuickMenuButtonId.java
> +// Copyright 2020 The Triple Banana Authors. All rights reserved.
In my opinion, we should add `Button` to `LinearLayout` programmatically not xml.
I'm not sure whether the right way or not. In this case, can we use R.id.xxxx instead?

2020-12-20 15:04 UTC, jdragonbae commented on src/org/triple/banana/quick_menu/QuickMenuViewModelImpl.java
> +        Map<Integer, ButtonInfo> getButtons() {
Ack. Thanks!

2020-12-20 15:04 UTC, jdragonbae commented on src/org/triple/banana/quick_menu/QuickMenuControllerImpl.java
> +        mQuickMenuViewModel.getEditor().getButtons().put(QuickMenuButtonId.DARK_MODE,
Ack!

2020-12-21 06:02 UTC, romandev commented on banana_cake/interfaces/java/org/banana/cake/interfaces/BananaToolbarManager.java
> +    void openQuickMenu();
Ack.

2020-12-21 07:01 UTC, romandev commented on banana_cake/interfaces/java/org/banana/cake/interfaces/BananaToolbarManager.java
> +    void openQuickMenu();
I think that you could use `org.banana.cake.interfaces.BananaTabManager.get().getActivityTab().getContext()`

2020-12-21 08:09 UTC, jdragonbae commented on banana_cake/interfaces/java/org/banana/cake/interfaces/BananaToolbarManager.java
> +    void openQuickMenu();
Thanks for the guidance! Looks good way.

2020-12-21 08:09 UTC, jdragonbae commented on banana_cake/java/org/banana/cake/CakeToolbarManager.java
> +    public void openQuickMenu() {
Done.

2020-12-21 08:10 UTC, jdragonbae commented on src/org/triple/banana/quick_menu/QuickMenuButtonId.java
> +// Copyright 2020 The Triple Banana Authors. All rights reserved.
I learned a new way. Thank you!
I'll try to this way.

2020-12-21 08:10 UTC, jdragonbae commented on BUILD.gn
> +    "//triple_banana/src/org/triple/banana/quick_menu/QuickMenuButtonId.java",
Thanks. Done.

2020-12-21 09:12 UTC, romandev approved these changes
lgtm

2020-12-21 09:12 UTC, merged